name: dslink_mamac
description: Mamac Systems DSLink
environment:
  sdk: ">=1.11.0 <2.0.0"
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  xml: ^2.4.1
  http: '^0.11.3+3'
  quiver: '^0.21.4'
dev_dependencies:
  test: '^0.12.11+1'
